import pygame


"""
Animations for the ninga
"""

#Idle
imageListPlayer1 = []
imageListPlayer1.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/Idle/idle (1).png'))
imageListPlayer1.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/Idle/idle (2).png'))
imageListPlayer1.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/Idle/idle (3).png'))
imageListPlayer1.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/Idle/idle (4).png'))
imageListPlayer1.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/Idle/idle (5).png'))
imageListPlayer1.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/Idle/idle (6).png'))
imageListPlayer1.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/Idle/idle (7).png'))
imageListPlayer1.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/Idle/idle (8).png'))
imageListPlayer1.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/Idle/idle (9).png'))
imageListPlayer1.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/Idle/idle (10).png'))


#Walk
imageListPlayer2 = []
imageListPlayer2.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/walk-1/walk (1).png'))
imageListPlayer2.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/walk-1/walk (2).png'))
imageListPlayer2.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/walk-1/walk (3).png'))
imageListPlayer2.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/walk-1/walk (4).png'))
imageListPlayer2.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/walk-1/walk (5).png'))
imageListPlayer2.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/walk-1/walk (6).png'))
imageListPlayer2.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/walk-1/walk (7).png'))
imageListPlayer2.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/walk-1/walk (8).png'))
imageListPlayer2.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/walk-1/walk (9).png'))


#Punch
punchNingaAnim = []
punchNingaAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/punch/punch (1).png'))
punchNingaAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/punch/punch (2).png'))
punchNingaAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/punch/punch (3).png'))
punchNingaAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/punch/punch (4).png'))
punchNingaAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/punch/punch (5).png'))
punchNingaAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/punch/punch (6).png'))
punchNingaAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/punch/punch (7).png'))
punchNingaAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/punch/punch (8).png'))
punchNingaAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/punch/punch (9).png'))
punchNingaAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/Ninga/punch/punch (10).png'))


#Health
healthBarAnim = []
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (1).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (2).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (3).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (4).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (5).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (6).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (7).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (8).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (9).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (10).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (11).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (12).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (13).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (14).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (15).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (16).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (17).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (18).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (19).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (20).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (21).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (22).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (23).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (24).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (25).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (26).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (27).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (28).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (29).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (30).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (31).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (32).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (33).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (34).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (36).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (37).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (38).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (39).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (40).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (41).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (42).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (43).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (44).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (45).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (46).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (47).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (48).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (49).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (50).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (51).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (52).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (53).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (54).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (55).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (56).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (57).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (58).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (59).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (60).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (61).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (62).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (63).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (64).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (65).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (66).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (67).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (68).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (69).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (70).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (71).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (72).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (73).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (74).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (75).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (76).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (77).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (78).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (79).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (80).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (81).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (82).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (83).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (84).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (85).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (86).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (87).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (88).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (89).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (90).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (91).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (92).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (93).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (94).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (95).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (96).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (97).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (98).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (99).png'))
healthBarAnim.append(pygame.image.load('Z:/EdgyNigerianScammers/AnimationSheet/health/health (100).png'))


